name: Trigger Central Deploy

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy in actions-workflows repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_ACTIONS_WORKFLOWS }}" \
            https://api.github.com/repos/rvbasulto/actions-workflows/dispatches \
            -d '{"event_type":"deploy-app","client_payload":{"app":"nextjs-portfolio-app","ref":"master"}}'
