name: Deploy app to VPS on dispatch

on:
  repository_dispatch:
    types: [deploy-app]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.app_repo }}
          ref: ${{ github.event.client_payload.ref }}
          token: ${{ secrets.GH_PAT }}

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.client_payload.image_name }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.client_payload.image_name }}

      - name: SSH deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.client_payload.image_name }}
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            docker run -d --name nextjs-app -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.client_payload.image_name }}
