name: Reusable App Deployment Workflow

on:
  workflow_call:
    inputs:
      dockerhub_username:
        required: true
        type: string
      host:
        required: true
        type: string
      ssh_user:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true
      SSH_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.dockerhub_username }}/${{ inputs.image_name }} .

      - name: Push Docker image
        run: |
          docker push ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ inputs.host }}
          username: ${{ inputs.ssh_user }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            docker run -d --name nextjs-app -p 3000:3000 ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}
